# 2.2 Calculate the mean for each sample and answer the following two questions: 
- Is the mean of the means close to the mean of all the data in that variable? 
- Would you say that the distribution of the means has an approximately normal distribution?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
PATH = "../../../DataCleaning/"

In [3]:
poblacional = pd.read_csv(PATH + "Atmospheric Data With No Missing Values.csv")

In [4]:
PATH = "../2.1 Sampling/"

In [5]:
everydaySamples10_1 = pd.read_csv(PATH + "EverydaySamples10_1.csv")
everydaySamples10_2 = pd.read_csv(PATH + "EverydaySamples10_2.csv")
everydaySamples10_3 = pd.read_csv(PATH + "EverydaySamples10_3.csv")
everydaySamples100_1 = pd.read_csv(PATH + "EverydaySamples100_1.csv")
everydaySamples100_2 = pd.read_csv(PATH + "EverydaySamples100_2.csv")
everydaySamples100_3 = pd.read_csv(PATH + "EverydaySamples100_3.csv")
everydaySamples1000_1 = pd.read_csv(PATH + "EverydaySamples1000_1.csv")
everydaySamples1000_2 = pd.read_csv(PATH + "EverydaySamples1000_2.csv")
everydaySamples1000_3 = pd.read_csv(PATH + "EverydaySamples1000_3.csv")
everydaySamples10000_1 = pd.read_csv(PATH + "EverydaySamples10000_1.zip")
everydaySamples10000_2 = pd.read_csv(PATH + "EverydaySamples10000_2.zip")
everydaySamples10000_3 = pd.read_csv(PATH + "EverydaySamples10000_3.zip")
raining1 = pd.read_csv(PATH + "RainingSamples1.csv")
raining2 = pd.read_csv(PATH + "RainingSamples2.csv")
raining3 = pd.read_csv(PATH + "RainingSamples3.csv")
random10_1 = pd.read_csv(PATH + "RandomSample10_1.csv")
random10_2 = pd.read_csv(PATH + "RandomSample10_2.csv")
random10_3 = pd.read_csv(PATH + "RandomSample10_3.csv")
random100_1 = pd.read_csv(PATH + "RandomSample100_1.csv")
random100_2 = pd.read_csv(PATH + "RandomSample100_2.csv")
random100_3 = pd.read_csv(PATH + "RandomSample100_3.csv")
random1000_1 = pd.read_csv(PATH + "RandomSample1000_1.csv")
random1000_2 = pd.read_csv(PATH + "RandomSample1000_2.csv")
random1000_3 = pd.read_csv(PATH + "RandomSample1000_3.csv")
random10000_1 = pd.read_csv(PATH + "RandomSample10000_1.csv")
random10000_2 = pd.read_csv(PATH + "RandomSample10000_2.csv")
random10000_3 = pd.read_csv(PATH + "RandomSample10000_3.csv")
random100000_1 = pd.read_csv(PATH + "RandomSample100000_1.csv")
random100000_2 = pd.read_csv(PATH + "RandomSample100000_2.csv")
random100000_3 = pd.read_csv(PATH + "RandomSample100000_3.csv")

In [8]:
variables = ["O3", "NO2", "NO", "CO", "PM10", "PM2.5", "Temp_Avg", "RH_Avg", "WSpeed_Avg", "WDir_Avg", "Rain_Tot", "Press_Avg", "Rad_Avg"]

In [34]:
meanPoblacional = list(poblacional[variables].mean())
meanPoblacional

[34.1781475982395,
 4.826200361662021,
 0.8407245190616629,
 0.3305503395654644,
 24.375818632358374,
 17.433051218918262,
 18.340548549293363,
 60.65806376435147,
 1.5642836724478482,
 144.94631321870182,
 0.0010338032233916862,
 805.8385776107762,
 471.9045388241155]

In [12]:
files = [everydaySamples10_1, everydaySamples10_2, everydaySamples10_3,
         everydaySamples100_1, everydaySamples100_2, everydaySamples100_3,
         everydaySamples1000_1, everydaySamples1000_2, everydaySamples1000_3,
         everydaySamples10000_1, everydaySamples10000_2, everydaySamples10000_3,
         raining1, raining2, raining3,
         random10_1, random10_2, random10_3,
         random100_1, random100_2, random100_3,
         random1000_1, random1000_2, random1000_3,
         random10000_1, random10000_2, random10000_3,
         random100000_1, random100000_2, random100000_3]

In [32]:
means = [np.array(f[variables].mean()) for f in files]
means

[array([3.39537238e+01, 4.80486667e+00, 8.49726984e-01, 3.32063492e-01,
        2.45471111e+01, 1.72856762e+01, 1.83393546e+01, 6.07711397e+01,
        1.56010889e+00, 1.44480937e+02, 1.14285714e-03, 8.05820350e+02,
        4.48513915e+02]),
 array([3.34905238e+01, 4.86587302e+00, 8.57663492e-01, 3.30314286e-01,
        2.46139206e+01, 1.76784095e+01, 1.81932432e+01, 6.11134413e+01,
        1.53279587e+00, 1.40993514e+02, 1.14285714e-03, 8.05847392e+02,
        4.72046647e+02]),
 array([3.39534952e+01, 4.77093651e+00, 8.15638095e-01, 3.30892063e-01,
        2.47825143e+01, 1.77189651e+01, 1.82973829e+01, 6.09234540e+01,
        1.55049937e+00, 1.44021276e+02, 9.20634921e-04, 8.05823052e+02,
        4.61262895e+02]),
 array([3.41067587e+01, 4.85249175e+00, 8.47248571e-01, 3.31204762e-01,
        2.45807641e+01, 1.75700178e+01, 1.82920996e+01, 6.08127485e+01,
        1.54361114e+00, 1.44779621e+02, 9.49206349e-04, 8.05826730e+02,
        4.72439537e+02]),
 array([3.40513783e+01, 4.845262

In [33]:
meanOfMeans = [np.array([means[0][i], means[1][i], means[2][i], means[3][i], means[4][i], means[5][i], means[6][i], means[7][i], means[8][i], means[9][i], means[10][i], means[11][i], means[12][i]]) for i in range(13)]
meanOfMeans = [m.mean() for m in meanOfMeans]
meanOfMeans

[33.906531759829065,
 4.736096747008547,
 0.7984409167277167,
 0.32614570354090355,
 24.01584712405372,
 17.36056022051282,
 18.1118896204884,
 62.86038294168499,
 1.6115058093040295,
 145.71287533421247,
 0.014445289377289379,
 805.8768804247619,
 436.32018189528674]

## Is the mean of the means close to the mean of all the data in that variable?

In [35]:
for i in range(13):
    print(f"Difference {variables[i]}: {abs(meanPoblacional[i] - meanOfMeans[i])}")

Difference O3: 0.27161583841043324
Difference NO2: 0.09010361465347394
Difference NO: 0.042283602333946235
Difference CO: 0.004404636024560871
Difference PM10: 0.3599715083046533
Difference PM2.5: 0.07249099840544204
Difference Temp_Avg: 0.2286589288049612
Difference RH_Avg: 2.2023191773335213
Difference WSpeed_Avg: 0.047222136856181374
Difference WDir_Avg: 0.7665621155106521
Difference Rain_Tot: 0.013411486153897692
Difference Press_Avg: 0.03830281398575153
Difference Rad_Avg: 35.584356928828754


As we can see, most of the variables have very similar values. Only in Rad_Avg is there a significant difference between the means of the samples and the population mean.

These results are a product of the central limit theorem.

## Would you say that the distribution of the means has an approximately normal distribution?

Based on the central limit theorem, we can say that yes (depending on the number of sample means), the distribution of the means is approximately normal.

We can verify this by conducting normality tests (Shapiro-Wilk) in an R script.